[package]
name = "http-common"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Arnavion <me@arnavion.dev>"]
edition = "2018"
publish = false


[dependencies]
anyhow = "1"
base64 = "0.13"
chrono = "0.4"
ct-logs = "0.8"
http = "0.2"
hyper = { version = "0.14", features = ["http1", "client"] }
hyper-rustls = { version = "0.22", default-features = false, features = ["webpki-tokio"] }
once_cell = "1"
rustls = "0.19"
serde = "1"
serde_json = "1"
webpki-roots = "0.21"
