[package]
name = "azure"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Arnavion <me@arnavion.dev>"]
edition = "2018"
publish = false


[dependencies]
anyhow = { version = "1", optional = true }
base64 = { version = "0.13", optional = true }
chrono = { version = "0.4", optional = true }
form_urlencoded = { version = "1", optional = true }
hyper = { version = "0.14", features = ["http1", "client"], optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
tokio = { version = "1", features = ["time"], optional = true }

http-common = { path = "../http-common", optional = true }


[features]
cdn = ["serde_json", "tokio", "_common"]
dns = ["_common"]
key_vault_cert = ["base64", "chrono", "serde_json", "_common"]
key_vault_key = ["serde_json", "_common"]

_common = ["anyhow", "form_urlencoded", "hyper", "serde", "http-common"]
