[package]
name = "azure"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Arnavion <me@arnavion.dev>"]
edition = "2018"
publish = false


[dependencies]
anyhow = { version = "1", optional = true, default-features = false, features = [
	"std", # for <E: std::error::Error>Result<_, E>: anyhow::Context
] }
base64 = { version = "0.13", optional = true, default-features = false }
chrono = { version = "0.4", optional = true, default-features = false }
form_urlencoded = { version = "1", optional = true, default-features = false }
futures-util = { version = "0.3", optional = true, default-features = false }
hmac = { version = "0.10", optional = true, default-features = false }
http = { version = "0.2", optional = true, default-features = false }
hyper = { version = "0.14", optional = true, default-features = false, features = [
	"stream",
] }
log = { version = "0.4", optional = true, default-features = false }
serde = { version = "1", optional = true, default-features = false, features = [
	"derive",
] }
serde_json = { version = "1", optional = true, default-features = false, features = [
	"std", # for serde_json::Error: std::error::Error
] }
sha2 = { version = "0.9", optional = true, default-features = false, features = [
	"std", # for sha2::Sha256: std::io::Write
] }
tokio = { version = "1", optional = true, default-features = false, features = [
	"parking_lot", # for slimmer tokio::sync::RwLock
	"sync",
	"time",
] }

acme = { path = "../acme", optional = true }
http-common = { path = "../http-common", optional = true }
log2 = { path = "../log2", optional = true }
once_cell2 = { path = "../once_cell2", optional = true }


[features]
cdn = ["_common"]
dns = ["_common"]
key_vault_cert = ["base64", "chrono", "_common"]
key_vault_key = ["acme", "_common"]
log_analytics = ["base64", "chrono", "chrono/clock", "futures-util", "hmac", "hyper", "log", "sha2", "_common"]

_common = ["anyhow", "form_urlencoded", "http", "serde", "serde_json", "tokio", "http-common", "log2", "once_cell2"]
