[workspace]
members = [
	"acme",
	"azure",
	"function-worker",
	"http-common",
	"log2",
	"time2",

	"function-renew-cert",
]
resolver = "2"

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = "s"
panic = "abort"
strip = "symbols"
