[package]
name = "function-worker"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Arnavion <me@arnavion.dev>"]
edition = "2018"
publish = false


[dependencies]
anyhow = { version = "1", default-features = false, features = [
	"std", # for <E: std::error::Error>Result<_, E>: anyhow::Context
] }
hyper = { version = "0.14", default-features = false, features = [
	"http1",
	"server",
	"tcp", # for hyper::Server::try_bind
] }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false, features = [
	"std", # for serde_json::Error: std::error::Error
] }
tokio = { version = "1", default-features = false, features = [
	"rt",
] }

http-common = { path = "../http-common" }
