[package]
name = "function-worker"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Arnavion <me@arnavion.dev>"]
edition = "2018"
publish = false


[dependencies]
anyhow = "1"
hyper = { version = "0.14", features = ["http1", "server", "tcp"] }
serde = "1"
serde_json = "1"
tokio = "1"

http-common = { path = "../http-common" }
