[package]
name = "function-renew-cert"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Arnavion <me@arnavion.dev>"]
edition = "2018"
publish = false


[dependencies]
anyhow = { version = "1", default-features = false, features = [
	"std", # for <E: std::error::Error>Result<_, E>: anyhow::Context
] }
base64 = { version = "0.13", default-features = false, features = [
	"std", # for base64::read, base64::write
] }
chrono = { version = "0.4", default-features = false, features = [
	"clock", # for chrono::Utc::now()
] }
http = { version = "0.2", default-features = false }
serde = { version = "1", default-features = false, features = [
	"derive",
] }
serde_json = { version = "1", default-features = false, features = [
	"std", # for serde_json::Error: std::error::Error
] }
sha2 = { version = "0.9", default-features = false }
tokio = { version = "1", default-features = false, features = [
	"time",
] }

acme = { path = "../acme" }
azure = { path = "../azure", features = [
	"dns",
	"key_vault_cert",
	"key_vault_key",
] }
function-worker = { path = "../function-worker" }
http-common = { path = "../http-common" }
log2 = { path = "../log2" }
once_cell2 = { path = "../once_cell2" }
