# TODO: Replace with `strip = "symbols"` in `[profile.release]` section when that is stabilized.
#
# Ref: https://github.com/rust-lang/rust/issues/72110
[target.'x86_64-unknown-linux-musl']
rustflags = ["-C", "link-arg=-s"]
