[package]
name = "acme"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Arnavion <me@arnavion.dev>"]
edition = "2018"
publish = false


[dependencies]
anyhow = "1"
chrono = "0.4"
hyper = { version = "0.14" }
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = { version = "0.9", default-features = false }
tokio = { version = "1", features = ["macros", "rt"] }

azure = { path = "../azure", features = ["dns", "key_vault_cert", "key_vault_key"] }
function-host = { path = "../function-host" }
http-common = { path = "../http-common" }
