name: 'CI'

on:
  pull_request:
    branches:
    - 'master'
  push:
    branches:
    - 'master'
  workflow_dispatch:

jobs:
  test:
    runs-on: 'ubuntu-24.04'

    steps:
    - uses: 'actions/checkout@v5'

    - name: 'Run'
      run: |
        set -euo pipefail

        rustup self update
        rustup set profile minimal
        rustup update

        cargo install --locked cargo-machete

        make SHELL=/bin/bash test
