name: 'CI'

on:
  pull_request:
    branches:
    - 'master'
  push:
    branches:
    - 'master'
  workflow_dispatch:

jobs:
  test:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: 'actions/checkout@v2'

    - name: 'Run'
      run: |
        set -euo pipefail

        rustup self update
        rustup set profile minimal

        make SHELL=/bin/bash test
